[package]
name = "sh_exif_tool"
version = "0.1.0"
edition = "2021"

#[dependencies]
#eframe = "0.27"
#regex = "1.7"
#rexiv2 = "0.10.0"
#image = "0.24.6"
#unicode-width = "0.1"
#time = { version = "0.3", features = ["macros", "formatting", "parsing"] }

[dependencies]
egui_extras = "0.30"
chrono = "0.4"
slint = { version = "1.9", optional = true }
eframe = { version = "0.30", optional = true }

[build-dependencies]
slint-build = "1"

[features]
default = ["gui-slint"]
gui-slint = ["dep:slint"]
gui-egui = ["dep:eframe"]

[package.metadata.slint]
include-path = ["src/gui_slint"]